storage: /verdaccio/storage/data
plugins: /verdaccio/plugins

web:
  title: ez local npm

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd
    max_users: 1000

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  'ezenciel-*':
    access: $all
    publish: $all
    unpublish: $all
  '@ezenciel/*':
    access: $all
    publish: $all
    unpublish: $all
  '**':
    access: $all
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: false

log:
  type: stdout
  format: pretty
  level: http
