import { WorkforceWatch, WorkforceWatchServer } from './workforce-watch.js'
import { readFileSync } from 'node:fs'
const positive=(value:string|undefined,name:string,fallback:number):number=>{if(!value)return fallback;const parsed=Number(value);if(!Number.isSafeInteger(parsed)||parsed<=0)throw new Error(`${name} must be a positive integer`);return parsed}
const pagerDutyRoutingKey=()=>{const secretFile='/run/secrets/workforce_watch_pagerduty';try{const value=readFileSync(secretFile,'utf8').trim();if(!value||/[\r\n]/.test(value))throw new Error('Workforce PagerDuty secret must contain exactly one routing key');return value}catch(error){if((error as NodeJS.ErrnoException).code==='ENOENT')return undefined;throw error}}
const enrollmentToken=process.env.EZ_WATCH_ENROLL_TOKEN?.trim();if(!enrollmentToken)throw new Error('EZ_WATCH_ENROLL_TOKEN is required')
const telegramToken=process.env.TELEGRAM_BOT_TOKEN?.trim(),telegramChatId=process.env.EZ_WATCH_TELEGRAM_CHAT_ID?.trim();if(Boolean(telegramToken)!==Boolean(telegramChatId))throw new Error('Set both TELEGRAM_BOT_TOKEN and EZ_WATCH_TELEGRAM_CHAT_ID, or neither')
const routingKey=pagerDutyRoutingKey()
const notify=telegramToken&&telegramChatId?async(text:string)=>{const response=await fetch(`https://api.telegram.org/bot${telegramToken}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:telegramChatId,text,disable_web_page_preview:true}),redirect:'error',signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error(`Telegram delivery returned HTTP ${response.status}`)}:undefined
const page=routingKey?async(event:import('./workforce-watch.js').WorkforcePage)=>{const response=await fetch('https://events.pagerduty.com/v2/enqueue',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({routing_key:routingKey,event_action:event.action,dedup_key:event.dedupKey,payload:{summary:event.summary,source:event.source,severity:event.severity,component:event.dedupKey.slice('ez:workforce:'.length),custom_details:event.customDetails}}),redirect:'error',signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error(`PagerDuty delivery returned HTTP ${response.status}`)}:undefined
if(!page)throw new Error('Mount the workforce PagerDuty secret at /run/secrets/workforce_watch_pagerduty')
const watch=new WorkforceWatch({stateDir:process.env.EZ_WATCH_STATE_DIR?.trim()||'/state',enrollmentToken,recoveryThreshold:positive(process.env.EZ_WATCH_RECOVERY_CHECKS,'EZ_WATCH_RECOVERY_CHECKS',2),notify,page,log:message=>console.error(message)})
const port=positive(process.env.EZ_WATCH_PORT,'EZ_WATCH_PORT',8080),host=process.env.EZ_WATCH_HOST?.trim()||'0.0.0.0',evaluateMs=positive(process.env.EZ_WATCH_EVALUATE_SECONDS,'EZ_WATCH_EVALUATE_SECONDS',30)*1000,server=new WorkforceWatchServer(watch,enrollmentToken)
await server.listen(port,host);watch.start(evaluateMs);console.log(`Workforce Watch listening on ${host}:${port}`)
for(const signal of ['SIGINT','SIGTERM'] as const)process.once(signal,()=>{watch.stop();void server.close().finally(()=>process.exit(0))})
